/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "ERGASIA.h"

bool_t
xdr_vector_in (XDR *xdrs, vector_in *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->y.y_val, (u_int *) &objp->y.y_len, ~0,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->a))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_minmax (XDR *xdrs, minmax *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->mima.mima_val, (u_int *) &objp->mima.mima_len, 2,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_product (XDR *xdrs, product *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->prod.prod_val, (u_int *) &objp->prod.prod_len, ~0,
		sizeof (float), (xdrproc_t) xdr_float))
		 return FALSE;
	return TRUE;
}
